// <auto-generated />
using Examweb_PhamDucTrong.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Examweb_PhamDucTrong.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250612064624_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Examweb_PhamDucTrong.Models.DiaNhac", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("GiaBan")
                        .HasColumnType("float");

                    b.Property<string>("NgheSi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<bool>("TrongNuoc")
                        .HasColumnType("bit");

                    b.Property<string>("TuaCD")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.ToTable("DiaNhacs");
                    b.HasData(new
                    {
                        Id = 1,
                        TuaCD = "Cổ điển",
                        NgheSi = "a",
                        TrongNuoc = 0,
                        GiaBan = 1000,
                        SoLuong = 2
                    },
                    new
                    {
                        Id = 1,
                        TuaCD = "Hại điện",
                        NgheSi = "a",
                        TrongNuoc = 0,
                        GiaBan = 1000,
                        SoLuong = 2
                    },
                    new
                    {
                        Id = 1,
                        TuaCD = "á",
                        NgheSi = "a",
                        TrongNuoc = 0,
                        GiaBan = 1000,
                        SoLuong = 2
                    },
                    new
                    {
                        Id = 1,
                        TuaCD = "Cổ đại",
                        NgheSi = "a",
                        TrongNuoc = 0,
                        GiaBan = 1000,
                        SoLuong = 2
                    },
                    new
                    {
                        Id = 1,
                        TuaCD = "hiện đại",
                        NgheSi = "a",
                        TrongNuoc = 0,
                        GiaBan = 1000,
                        SoLuong = 2
                    });
                });
#pragma warning restore 612, 618
        }
    }
}
