// <auto-generated />
using Examweb_PhamDucTrong.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Examweb_PhamDucTrong.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ExamWeb_DuongTuLuc.Models.DiaNhac", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("GiaBan")
                        .HasColumnType("float");

                    b.Property<string>("NgheSi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<bool>("TrongNuoc")
                        .HasColumnType("bit");

                    b.Property<string>("TuaCD")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.ToTable("DiaNhacs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GiaBan = 250000.0,
                            NgheSi = "Dương Thanh Nam",
                            SoLuong = 20,
                            TrongNuoc = true,
                            TuaCD = "CD Bản tình ca trong đêm"
                        },
                        new
                        {
                            Id = 2,
                            GiaBan = 105000.0,
                            NgheSi = "Võ Văn Dương",
                            SoLuong = 15,
                            TrongNuoc = true,
                            TuaCD = "CD Nổi buồn gác trọ"
                        },
                        new
                        {
                            Id = 3,
                            GiaBan = 500000.0,
                            NgheSi = "The Weekend",
                            SoLuong = 30,
                            TrongNuoc = false,
                            TuaCD = "CD Today's US-UK Hit"
                        },
                        new
                        {
                            Id = 4,
                            GiaBan = 150000.0,
                            NgheSi = "Phương Mỹ Chi",
                            SoLuong = 20,
                            TrongNuoc = true,
                            TuaCD = "CD Chuyện chúng mình"
                        },
                        new
                        {
                            Id = 5,
                            GiaBan = 400000.0,
                            NgheSi = "WonYoung",
                            SoLuong = 50,
                            TrongNuoc = false,
                            TuaCD = "CD BabyMonster"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
